
insert into nyc_streets values(1,'Shore Pky S','','residential');
insert into nyc_streets values(2,'','','footway');
insert into nyc_streets values(3,'Avenue O','','residential');
insert into nyc_streets values(4,'Walsh Ct','','residential');
insert into nyc_streets values(5,'','','motorway_link');
insert into nyc_streets values(6,'Avenue Z','','residential');
insert into nyc_streets values(7,'Dank Ct','','residential');
insert into nyc_streets values(8,'Cumberland Walk','','footway');
insert into nyc_streets values(9,'Cumberland Walk','','footway');
insert into nyc_streets values(10,'','','residential');
insert into nyc_streets values(11,'Cobek Ct','','residential');
insert into nyc_streets values(12,'','','footway');
insert into nyc_streets values(13,'Avenue Y','','residential');
insert into nyc_streets values(14,'Sherman St','','residential');
insert into nyc_streets values(15,'Bouck Ct','','residential');
insert into nyc_streets values(16,'Montgomery Pl','','residential');
insert into nyc_streets values(17,'W 97th St','','residential');
insert into nyc_streets values(18,'Riverside Dr','','residential');
insert into nyc_streets values(19,'','','service');
insert into nyc_streets values(20,'West Dr','yes','residential');
insert into nyc_streets values(21,'Lake St','','residential');
insert into nyc_streets values(22,'S Oxford St','','residential');
insert into nyc_streets values(23,'West 58th St','','residential');
insert into nyc_streets values(24,'Grand Army Plz','','residential');
insert into nyc_streets values(25,'Central Dr','','residential');
insert into nyc_streets values(26,'Avenue N','','residential');
insert into nyc_streets values(27,'E 10th St','','residential');
insert into nyc_streets values(28,'','','motorway_link');
insert into nyc_streets values(29,'E 57th St','','primary');
insert into nyc_streets values(30,'','','footway');
insert into nyc_streets values(31,'','','footway');
insert into nyc_streets values(32,'Washington Park','','residential');
insert into nyc_streets values(33,'E 8th St','','residential');
insert into nyc_streets values(34,'','','service');
insert into nyc_streets values(35,'Carlton Ave','','residential');
insert into nyc_streets values(36,'E 2nd St','','residential');
insert into nyc_streets values(37,'Tunnel Entrance St','','residential');
insert into nyc_streets values(38,'Ryder Ave','','residential');
insert into nyc_streets values(39,'Central Park Driveway','','residential');
insert into nyc_streets values(40,'E 7th St','','residential');
insert into nyc_streets values(41,'','','steps');
insert into nyc_streets values(42,'W 98th St','','residential');
insert into nyc_streets values(43,'Central Pk-Ctr Dr','yes','residential');
insert into nyc_streets values(44,'Central Park-Center Dr; Central Park Driveway','','residential');
insert into nyc_streets values(45,'Grand Army Plz','','residential');
insert into nyc_streets values(46,'','','footway');
insert into nyc_streets values(47,'','','footway');
insert into nyc_streets values(48,'Market St','','residential');
insert into nyc_streets values(49,'W 100 St','','residential');
insert into nyc_streets values(50,'','','residential');
