 insert into nyc_neighborhoods values('Brooklyn','Bensonhurst');
insert into nyc_neighborhoods values('Manhattan','East Village');
insert into nyc_neighborhoods values('Manhattan','West Village');
insert into nyc_neighborhoods values('The Bronx','Throggs Neck');
insert into nyc_neighborhoods values('The Bronx','Wakefield-Williamsbridge');
insert into nyc_neighborhoods values('Queens','Auburndale');
insert into nyc_neighborhoods values('Manhattan','Battery Park');
insert into nyc_neighborhoods values('Manhattan','Carnegie Hill');
insert into nyc_neighborhoods values('Staten Island','Mariners Harbor');
insert into nyc_neighborhoods values('Staten Island','Rossville');
insert into nyc_neighborhoods values('Manhattan','Harlem');
insert into nyc_neighborhoods values('Manhattan','Gramercy');
insert into nyc_neighborhoods values('Queens','Queens Village');
insert into nyc_neighborhoods values('Queens','Middle Village');
insert into nyc_neighborhoods values('Staten Island','Ettingville');
insert into nyc_neighborhoods values('The Bronx','Morris Park');
insert into nyc_neighborhoods values('The Bronx','Baychester');
insert into nyc_neighborhoods values('Staten Island','Great Kills');
insert into nyc_neighborhoods values('Staten Island','New Brighton');
insert into nyc_neighborhoods values('The Bronx','Fordham');
insert into nyc_neighborhoods values('Queens','Nkew Gardens');
insert into nyc_neighborhoods values('Manhattan','Soho');
insert into nyc_neighborhoods values('The Bronx','Spuyten Duyvil');
insert into nyc_neighborhoods values('Queens','Woodside');
insert into nyc_neighborhoods values('Brooklyn','Bay Ridge');
insert into nyc_neighborhoods values('The Bronx','Mott Haven');
insert into nyc_neighborhoods values('Queens','Rosedale');
insert into nyc_neighborhoods values('Brooklyn','Boerum Hill');
insert into nyc_neighborhoods values('Brooklyn','Cobble Hill');
insert into nyc_neighborhoods values('Manhattan','Morningside Heights');
insert into nyc_neighborhoods values('Manhattan','Murray Hill');
insert into nyc_neighborhoods values('Staten Island','Port Richmond');
insert into nyc_neighborhoods values('The Bronx','Williams Bridge');
insert into nyc_neighborhoods values('Brooklyn','Downtown');
insert into nyc_neighborhoods values('Staten Island','Woodrow');
insert into nyc_neighborhoods values('The Bronx','Union Port');
insert into nyc_neighborhoods values('Queens','Woodhaven-Richmond Hill');
insert into nyc_neighborhoods values('The Bronx','Soundview');
insert into nyc_neighborhoods values('Queens','Jamaica');
insert into nyc_neighborhoods values('Queens','Laurelton');
insert into nyc_neighborhoods values('Brooklyn','Sunset Park');
insert into nyc_neighborhoods values('Brooklyn','Borough Park');
insert into nyc_neighborhoods values('Brooklyn','East Brooklyn');
insert into nyc_neighborhoods values('Staten Island','Midland Beach');
insert into nyc_neighborhoods values('Queens','Jackson Heights');
insert into nyc_neighborhoods values('Queens','Maspeth');
insert into nyc_neighborhoods values('Brooklyn','Flatbush');
insert into nyc_neighborhoods values('Manhattan','Central Park');
insert into nyc_neighborhoods values('Staten Island','Charlestown-Richmond Valley');
insert into nyc_neighborhoods values('Queens','Glendale');
